using System;
using Modelo;
using System.Data.OracleClient;

namespace DAL
{
    public class DALPCORIGEMPRECO
    {
        public DALConexao conexao;
        public DALPCORIGEMPRECO (DALConexao cx)
        {
            this.conexao = cx;
        }

        public void Incluir(ModeloPCORIGEMPRECO modelo)
        {
            String comando1 = "";

#pragma warning disable CS0618 // "OracleCommand" é obsoleto: "OracleCommand has been deprecated. http://go.microsoft.com/fwlink/?LinkID=144260"
#pragma warning disable CS0618 // "OracleCommand" é obsoleto: "OracleCommand has been deprecated. http://go.microsoft.com/fwlink/?LinkID=144260"
            OracleCommand cmd = new OracleCommand();
#pragma warning restore CS0618 // "OracleCommand" é obsoleto: "OracleCommand has been deprecated. http://go.microsoft.com/fwlink/?LinkID=144260"
#pragma warning restore CS0618 // "OracleCommand" é obsoleto: "OracleCommand has been deprecated. http://go.microsoft.com/fwlink/?LinkID=144260"
            cmd.Connection = conexao.ObjetoConexao;

            comando1 = comando1 + "INSERT INTO PCORIGEMPRECO " + "\n";
            comando1 = comando1 + "     ( " + "\n";
            comando1 = comando1 + "    CODAUTORIZACAO " + "\n";
            comando1 = comando1 + "    ,CODDESCFLEX " + "\n";
            comando1 = comando1 + "    ,CODDESCPBASE " + "\n";
            comando1 = comando1 + "    ,CODDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,CODEMITENTE " + "\n";
            comando1 = comando1 + "    ,CODFIGVENDATRIANGULAR " + "\n";
            comando1 = comando1 + "    ,CODFILIAL " + "\n";
            comando1 = comando1 + "    ,CODFILIALNF " + "\n";
            comando1 = comando1 + "    ,CODFISCAL " + "\n";
            comando1 = comando1 + "    ,CODPRECOFIXO " + "\n";
            comando1 = comando1 + "    ,CODPROD " + "\n";
            comando1 = comando1 + "    ,CODROTINADESCFLEX " + "\n";
            comando1 = comando1 + "    ,CODROTINADESCPTABELA " + "\n";
            comando1 = comando1 + "    ,CODROTINAPBASE " + "\n";
            comando1 = comando1 + "    ,COLUNAPRECO " + "\n";
            comando1 = comando1 + "    ,CREDITAPOLITICAPBASE " + "\n";
            comando1 = comando1 + "    ,DATA " + "\n";
            comando1 = comando1 + "    ,DTFIMAUTOR " + "\n";
            comando1 = comando1 + "    ,DTFIMDESCFLEX " + "\n";
            comando1 = comando1 + "    ,DTFIMDESCPBASE " + "\n";
            comando1 = comando1 + "    ,DTFIMDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,DTFIMDESCVOLUME " + "\n";
            comando1 = comando1 + "    ,DTFIMOFERTA " + "\n";
            comando1 = comando1 + "    ,DTINICIOAUTOR " + "\n";
            comando1 = comando1 + "    ,DTINICIODESCFLEX " + "\n";
            comando1 = comando1 + "    ,DTINICIODESCPBASE " + "\n";
            comando1 = comando1 + "    ,DTINICIODESCPTABELA " + "\n";
            comando1 = comando1 + "    ,DTINICIODESCVOLUME " + "\n";
            comando1 = comando1 + "    ,DTINICIOOFERTA " + "\n";
            comando1 = comando1 + "    ,FATORPRECO " + "\n";
            comando1 = comando1 + "    ,FIMINTERVALO " + "\n";
            comando1 = comando1 + "    ,FIMINTERVALOAUTORI " + "\n";
            comando1 = comando1 + "    ,FIMINTERVALOPBASE " + "\n";
            comando1 = comando1 + "    ,FIMINTERVALOPTABELA " + "\n";
            comando1 = comando1 + "    ,INICIOINTERVALO " + "\n";
            comando1 = comando1 + "    ,INICIOINTERVALOAUTORI " + "\n";
            comando1 = comando1 + "    ,INICIOINTERVALOPBASE " + "\n";
            comando1 = comando1 + "    ,INICIOINTERVALOPTABELA " + "\n";
            comando1 = comando1 + "    ,NAODEBITAPOLITICAPBASE " + "\n";
            comando1 = comando1 + "    ,NUMPED " + "\n";
            comando1 = comando1 + "    ,NUMREGIAO " + "\n";
            comando1 = comando1 + "    ,NUMSEQ " + "\n";
            comando1 = comando1 + "    ,ORIGEMPED " + "\n";
            comando1 = comando1 + "    ,ORIGEMPEDFLEX " + "\n";
            comando1 = comando1 + "    ,ORIGEMPEDPBASE " + "\n";
            comando1 = comando1 + "    ,ORIGEMPEDPTABELA " + "\n";
            comando1 = comando1 + "    ,ORIGEMPRECO " + "\n";
            comando1 = comando1 + "    ,PERACRESCISMOSIMPNAC " + "\n";
            comando1 = comando1 + "    ,PERBONIFIC " + "\n";
            comando1 = comando1 + "    ,PERCACRESCBALCAO " + "\n";
            comando1 = comando1 + "    ,PERCACRESCIMOTELEMARKETING " + "\n";
            comando1 = comando1 + "    ,PERCACRESCPF " + "\n";
            comando1 = comando1 + "    ,PERCDESCABATIMENTO " + "\n";
            comando1 = comando1 + "    ,PERCDESCAUTOR " + "\n";
            comando1 = comando1 + "    ,PERCDESCCOFINS " + "\n";
            comando1 = comando1 + "    ,PERCDESCFLEX " + "\n";
            comando1 = comando1 + "    ,PERCDESCPBASE " + "\n";
            comando1 = comando1 + "    ,PERCDESCPIS " + "\n";
            comando1 = comando1 + "    ,PERCDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,PERCDESCVOLUME " + "\n";
            comando1 = comando1 + "    ,PERCFRETE " + "\n";
            comando1 = comando1 + "    ,PERCPLPAG " + "\n";
            comando1 = comando1 + "    ,PERCRAMOATIV " + "\n";
            comando1 = comando1 + "    ,PERCREDALIQIPI " + "\n";
            comando1 = comando1 + "    ,PERDESCCOM " + "\n";
            comando1 = comando1 + "    ,PORIGINAL " + "\n";
            comando1 = comando1 + "    ,QTMINATACADO " + "\n";
            comando1 = comando1 + "    ,SITTRIBUT " + "\n";
            comando1 = comando1 + "    ,TIPOBROKER " + "\n";
            comando1 = comando1 + "    ,TIPODESCFLEX " + "\n";
            comando1 = comando1 + "    ,TIPODESCPBASE " + "\n";
            comando1 = comando1 + "    ,TIPODESCPTABELA " + "\n";
            comando1 = comando1 + "    ,TIPOFRETE " + "\n";
            comando1 = comando1 + "    ,USATRIBUTPORUF " + "\n";
            comando1 = comando1 + "    ,VLBONIFIC " + "\n";
            comando1 = comando1 + "    ,VLDESCABATIMENTO " + "\n";
            comando1 = comando1 + "    ,VLDESCCOM " + "\n";
            comando1 = comando1 + "    ,VLDESCICMS " + "\n";
            comando1 = comando1 + "    ,VLDESCREDUCAOCOFINS " + "\n";
            comando1 = comando1 + "    ,VLDESCREDUCAOPIS " + "\n";
            comando1 = comando1 + "    ,VLDIFALIQUOTAS " + "\n";
            comando1 = comando1 + "    ,VLICMSDIFALIQPART " + "\n";
            comando1 = comando1 + "    ,VLICMSPARTILHA " + "\n";
            comando1 = comando1 + "    ,VLIPI " + "\n";
            comando1 = comando1 + "    ,VLREDPVENDASIMPLESNA " + "\n";
            comando1 = comando1 + "    ,VLREPASSE " + "\n";
            comando1 = comando1 + "    ,VLST " + "\n";
            comando1 = comando1 + "    ,VLSUFRAMA " + "\n";
            comando1 = comando1 + "    ) " + "\n";
            comando1 = comando1 + "    VALUES " + "\n";
            comando1 = comando1 + "    ( " + "\n";
            comando1 = comando1 + "    :CODAUTORIZACAO " + "\n";
            comando1 = comando1 + "    ,:CODDESCFLEX " + "\n";
            comando1 = comando1 + "    ,:CODDESCPBASE " + "\n";
            comando1 = comando1 + "    ,:CODDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:CODEMITENTE " + "\n";
            comando1 = comando1 + "    ,:CODFIGVENDATRIANGULAR " + "\n";
            comando1 = comando1 + "    ,:CODFILIAL " + "\n";
            comando1 = comando1 + "    ,:CODFILIALNF " + "\n";
            comando1 = comando1 + "    ,:CODFISCAL " + "\n";
            comando1 = comando1 + "    ,:CODPRECOFIXO " + "\n";
            comando1 = comando1 + "    ,:CODPROD " + "\n";
            comando1 = comando1 + "    ,:CODROTINADESCFLEX " + "\n";
            comando1 = comando1 + "    ,:CODROTINADESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:CODROTINAPBASE " + "\n";
            comando1 = comando1 + "    ,:COLUNAPRECO " + "\n";
            comando1 = comando1 + "    ,:CREDITAPOLITICAPBASE " + "\n";
            comando1 = comando1 + "    ,:DATA " + "\n";
            comando1 = comando1 + "    ,:DTFIMAUTOR " + "\n";
            comando1 = comando1 + "    ,:DTFIMDESCFLEX " + "\n";
            comando1 = comando1 + "    ,:DTFIMDESCPBASE " + "\n";
            comando1 = comando1 + "    ,:DTFIMDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:DTFIMDESCVOLUME " + "\n";
            comando1 = comando1 + "    ,:DTFIMOFERTA " + "\n";
            comando1 = comando1 + "    ,:DTINICIOAUTOR " + "\n";
            comando1 = comando1 + "    ,:DTINICIODESCFLEX " + "\n";
            comando1 = comando1 + "    ,:DTINICIODESCPBASE " + "\n";
            comando1 = comando1 + "    ,:DTINICIODESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:DTINICIODESCVOLUME " + "\n";
            comando1 = comando1 + "    ,:DTINICIOOFERTA " + "\n";
            comando1 = comando1 + "    ,:FATORPRECO " + "\n";
            comando1 = comando1 + "    ,:FIMINTERVALO " + "\n";
            comando1 = comando1 + "    ,:FIMINTERVALOAUTORI " + "\n";
            comando1 = comando1 + "    ,:FIMINTERVALOPBASE " + "\n";
            comando1 = comando1 + "    ,:FIMINTERVALOPTABELA " + "\n";
            comando1 = comando1 + "    ,:INICIOINTERVALO " + "\n";
            comando1 = comando1 + "    ,:INICIOINTERVALOAUTORI " + "\n";
            comando1 = comando1 + "    ,:INICIOINTERVALOPBASE " + "\n";
            comando1 = comando1 + "    ,:INICIOINTERVALOPTABELA " + "\n";
            comando1 = comando1 + "    ,:NAODEBITAPOLITICAPBASE " + "\n";
            comando1 = comando1 + "    ,:NUMPED " + "\n";
            comando1 = comando1 + "    ,:NUMREGIAO " + "\n";
            comando1 = comando1 + "    ,:NUMSEQ " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPED " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPEDFLEX " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPEDPBASE " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPEDPTABELA " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPRECO " + "\n";
            comando1 = comando1 + "    ,:PERACRESCISMOSIMPNAC " + "\n";
            comando1 = comando1 + "    ,:PERBONIFIC " + "\n";
            comando1 = comando1 + "    ,:PERCACRESCBALCAO " + "\n";
            comando1 = comando1 + "    ,:PERCACRESCIMOTELEMARKETING " + "\n";
            comando1 = comando1 + "    ,:PERCACRESCPF " + "\n";
            comando1 = comando1 + "    ,:PERCDESCABATIMENTO " + "\n";
            comando1 = comando1 + "    ,:PERCDESCAUTOR " + "\n";
            comando1 = comando1 + "    ,:PERCDESCCOFINS " + "\n";
            comando1 = comando1 + "    ,:PERCDESCFLEX " + "\n";
            comando1 = comando1 + "    ,:PERCDESCPBASE " + "\n";
            comando1 = comando1 + "    ,:PERCDESCPIS " + "\n";
            comando1 = comando1 + "    ,:PERCDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:PERCDESCVOLUME " + "\n";
            comando1 = comando1 + "    ,:PERCFRETE " + "\n";
            comando1 = comando1 + "    ,:PERCPLPAG " + "\n";
            comando1 = comando1 + "    ,:PERCRAMOATIV " + "\n";
            comando1 = comando1 + "    ,:PERCREDALIQIPI " + "\n";
            comando1 = comando1 + "    ,:PERDESCCOM " + "\n";
            comando1 = comando1 + "    ,:PORIGINAL " + "\n";
            comando1 = comando1 + "    ,:QTMINATACADO " + "\n";
            comando1 = comando1 + "    ,:SITTRIBUT " + "\n";
            comando1 = comando1 + "    ,:TIPOBROKER " + "\n";
            comando1 = comando1 + "    ,:TIPODESCFLEX " + "\n";
            comando1 = comando1 + "    ,:TIPODESCPBASE " + "\n";
            comando1 = comando1 + "    ,:TIPODESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:TIPOFRETE " + "\n";
            comando1 = comando1 + "    ,:USATRIBUTPORUF " + "\n";
            comando1 = comando1 + "    ,:VLBONIFIC " + "\n";
            comando1 = comando1 + "    ,:VLDESCABATIMENTO " + "\n";
            comando1 = comando1 + "    ,:VLDESCCOM " + "\n";
            comando1 = comando1 + "    ,:VLDESCICMS " + "\n";
            comando1 = comando1 + "    ,:VLDESCREDUCAOCOFINS " + "\n";
            comando1 = comando1 + "    ,:VLDESCREDUCAOPIS " + "\n";
            comando1 = comando1 + "    ,:VLDIFALIQUOTAS " + "\n";
            comando1 = comando1 + "    ,:VLICMSDIFALIQPART " + "\n";
            comando1 = comando1 + "    ,:VLICMSPARTILHA " + "\n";
            comando1 = comando1 + "    ,:VLIPI " + "\n";
            comando1 = comando1 + "    ,:VLREDPVENDASIMPLESNA " + "\n";
            comando1 = comando1 + "    ,:VLREPASSE " + "\n";
            comando1 = comando1 + "    ,:VLST " + "\n";
            comando1 = comando1 + "    ,:VLSUFRAMA)";
            cmd.CommandText = comando1;
            cmd.Parameters.AddWithValue(":CODAUTORIZACAO", modelo.codautorizacao);
            cmd.Parameters.AddWithValue(":CODDESCFLEX", modelo.coddescflex);
            cmd.Parameters.AddWithValue(":CODDESCPBASE", modelo.coddescpbase);
            cmd.Parameters.AddWithValue(":CODDESCPTABELA", modelo.coddescptabela);
            cmd.Parameters.AddWithValue(":CODEMITENTE", modelo.codemitente);
            cmd.Parameters.AddWithValue(":CODFIGVENDATRIANGULAR", modelo.codfigvendatriangular);
            cmd.Parameters.AddWithValue(":CODFILIAL", modelo.codfilial);
            cmd.Parameters.AddWithValue(":CODFILIALNF", modelo.codfilialnf);
            cmd.Parameters.AddWithValue(":CODFISCAL", modelo.codfiscal);
            cmd.Parameters.AddWithValue(":CODPRECOFIXO", modelo.codprecofixo);
            cmd.Parameters.AddWithValue(":CODPROD", modelo.codprod);
            cmd.Parameters.AddWithValue(":CODROTINADESCFLEX", modelo.codrotinadescflex);
            cmd.Parameters.AddWithValue(":CODROTINADESCPTABELA", modelo.codrotinadescptabela);
            cmd.Parameters.AddWithValue(":CODROTINAPBASE", modelo.codrotinapbase);
            cmd.Parameters.AddWithValue(":COLUNAPRECO", modelo.colunapreco);
            cmd.Parameters.AddWithValue(":CREDITAPOLITICAPBASE", modelo.creditapoliticapbase);
            cmd.Parameters.AddWithValue(":DATA", modelo.data);
            cmd.Parameters.AddWithValue(":DTFIMAUTOR", modelo.dtfimautor);
            cmd.Parameters.AddWithValue(":DTFIMDESCFLEX", modelo.dtfimdescflex);
            cmd.Parameters.AddWithValue(":DTFIMDESCPBASE", modelo.dtfimdescpbase);
            cmd.Parameters.AddWithValue(":DTFIMDESCPTABELA", modelo.dtfimdescptabela);
            cmd.Parameters.AddWithValue(":DTFIMDESCVOLUME", modelo.dtfimdescvolume);
            cmd.Parameters.AddWithValue(":DTFIMOFERTA", modelo.dtfimoferta);
            cmd.Parameters.AddWithValue(":DTINICIOAUTOR", modelo.dtinicioautor);
            cmd.Parameters.AddWithValue(":DTINICIODESCFLEX", modelo.dtiniciodescflex);
            cmd.Parameters.AddWithValue(":DTINICIODESCPBASE", modelo.dtiniciodescpbase);
            cmd.Parameters.AddWithValue(":DTINICIODESCPTABELA", modelo.dtiniciodescptabela);
            cmd.Parameters.AddWithValue(":DTINICIODESCVOLUME", modelo.dtiniciodescvolume);
            cmd.Parameters.AddWithValue(":DTINICIOOFERTA", modelo.dtiniciooferta);
            cmd.Parameters.AddWithValue(":FATORPRECO", modelo.fatorpreco);
            cmd.Parameters.AddWithValue(":FIMINTERVALO", modelo.fimintervalo);
            cmd.Parameters.AddWithValue(":FIMINTERVALOAUTORI", modelo.fimintervaloautori);
            cmd.Parameters.AddWithValue(":FIMINTERVALOPBASE", modelo.fimintervalopbase);
            cmd.Parameters.AddWithValue(":FIMINTERVALOPTABELA", modelo.fimintervaloptabela);
            cmd.Parameters.AddWithValue(":INICIOINTERVALO", modelo.iniciointervalo);
            cmd.Parameters.AddWithValue(":INICIOINTERVALOAUTORI", modelo.iniciointervaloautori);
            cmd.Parameters.AddWithValue(":INICIOINTERVALOPBASE", modelo.iniciointervalopbase);
            cmd.Parameters.AddWithValue(":INICIOINTERVALOPTABELA", modelo.iniciointervaloptabela);
            cmd.Parameters.AddWithValue(":NAODEBITAPOLITICAPBASE", modelo.naodebitapoliticapbase);
            cmd.Parameters.AddWithValue(":NUMPED", modelo.numped);
            cmd.Parameters.AddWithValue(":NUMREGIAO", modelo.numregiao);
            cmd.Parameters.AddWithValue(":NUMSEQ", modelo.numseq);
            cmd.Parameters.AddWithValue(":ORIGEMPED", modelo.origemped);
            cmd.Parameters.AddWithValue(":ORIGEMPEDFLEX", modelo.origempedflex);
            cmd.Parameters.AddWithValue(":ORIGEMPEDPBASE", modelo.origempedpbase);
            cmd.Parameters.AddWithValue(":ORIGEMPEDPTABELA", modelo.origempedptabela);
            cmd.Parameters.AddWithValue(":ORIGEMPRECO", modelo.origempreco);
            cmd.Parameters.AddWithValue(":PERACRESCISMOSIMPNAC", modelo.peracrescismosimpnac);
            cmd.Parameters.AddWithValue(":PERBONIFIC", modelo.perbonific);
            cmd.Parameters.AddWithValue(":PERCACRESCBALCAO", modelo.percacrescbalcao);
            cmd.Parameters.AddWithValue(":PERCACRESCIMOTELEMARKETING", modelo.percacrescimotelemarketing);
            cmd.Parameters.AddWithValue(":PERCACRESCPF", modelo.percacrescpf);
            cmd.Parameters.AddWithValue(":PERCDESCABATIMENTO", modelo.percdescabatimento);
            cmd.Parameters.AddWithValue(":PERCDESCAUTOR", modelo.percdescautor);
            cmd.Parameters.AddWithValue(":PERCDESCCOFINS", modelo.percdesccofins);
            cmd.Parameters.AddWithValue(":PERCDESCFLEX", modelo.percdescflex);
            cmd.Parameters.AddWithValue(":PERCDESCPBASE", modelo.percdescpbase);
            cmd.Parameters.AddWithValue(":PERCDESCPIS", modelo.percdescpis);
            cmd.Parameters.AddWithValue(":PERCDESCPTABELA", modelo.percdescptabela);
            cmd.Parameters.AddWithValue(":PERCDESCVOLUME", modelo.percdescvolume);
            cmd.Parameters.AddWithValue(":PERCFRETE", modelo.percfrete);
            cmd.Parameters.AddWithValue(":PERCPLPAG", modelo.percplpag);
            cmd.Parameters.AddWithValue(":PERCRAMOATIV", modelo.percramoativ);
            cmd.Parameters.AddWithValue(":PERCREDALIQIPI", modelo.percredaliqipi);
            cmd.Parameters.AddWithValue(":PERDESCCOM", modelo.perdesccom);
            cmd.Parameters.AddWithValue(":PORIGINAL", modelo.poriginal);
            cmd.Parameters.AddWithValue(":QTMINATACADO", modelo.qtminatacado);
            cmd.Parameters.AddWithValue(":SITTRIBUT", modelo.sittribut);
            cmd.Parameters.AddWithValue(":TIPOBROKER", modelo.tipobroker);
            cmd.Parameters.AddWithValue(":TIPODESCFLEX", modelo.tipodescflex);
            cmd.Parameters.AddWithValue(":TIPODESCPBASE", modelo.tipodescpbase);
            cmd.Parameters.AddWithValue(":TIPODESCPTABELA", modelo.tipodescptabela);
            cmd.Parameters.AddWithValue(":TIPOFRETE", modelo.tipofrete);
            cmd.Parameters.AddWithValue(":USATRIBUTPORUF", modelo.usatributporuf);
            cmd.Parameters.AddWithValue(":VLBONIFIC", modelo.vlbonific);
            cmd.Parameters.AddWithValue(":VLDESCABATIMENTO", modelo.vldescabatimento);
            cmd.Parameters.AddWithValue(":VLDESCCOM", modelo.vldesccom);
            cmd.Parameters.AddWithValue(":VLDESCICMS", modelo.vldescicms);
            cmd.Parameters.AddWithValue(":VLDESCREDUCAOCOFINS", modelo.vldescreducaocofins);
            cmd.Parameters.AddWithValue(":VLDESCREDUCAOPIS", modelo.vldescreducaopis);
            cmd.Parameters.AddWithValue(":VLDIFALIQUOTAS", modelo.vldifaliquotas);
            cmd.Parameters.AddWithValue(":VLICMSDIFALIQPART", modelo.vlicmsdifaliqpart);
            cmd.Parameters.AddWithValue(":VLICMSPARTILHA", modelo.vlicmspartilha);
            cmd.Parameters.AddWithValue(":VLIPI", modelo.vlipi);
            cmd.Parameters.AddWithValue(":VLREDPVENDASIMPLESNA", modelo.vlredpvendasimplesna);
            cmd.Parameters.AddWithValue(":VLREPASSE", modelo.vlrepasse);
            cmd.Parameters.AddWithValue(":VLST", modelo.vlst);
            cmd.Parameters.AddWithValue(":VLSUFRAMA", modelo.vlsuframa);
            conexao.Conectar();
            cmd.ExecuteNonQuery();
            conexao.Desconectar();
        }
    }
}
